language: go
os:
  - linux
  - osx
go:
  - master
env:
  - GO111MODULE=on
services:
  - postgresql
  - mysql
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then psql -c 'CREATE DATABASE trdsql_test ENCODING 'utf8' TEMPLATE template0;' -U postgres && mysql -e 'CREATE DATABASE trdsql_test CHARACTER SET utf8mb4;'; fi
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y ; sudo apt-get install -y binutils-mingw-w64-x86-64 gcc-mingw-w64-base gcc-mingw-w64-x86-64 ; fi
script:
  - make test
before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make pkg ; elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make pkg_macOS ;fi
  - rm -f $TRAVIS_BUILD_DIR/dist/*.zip
  - cd ${TRAVIS_BUILD_DIR}/dist/ && for i in `ls .`; do cp ../README.md $i; cp ../config.json.sample $i; zip $i.zip $i/* ;done
deploy:
  provider: releases
  api_key:
    secure: Ssa2Xkxq6EGS02PMwmLC7tN2+tE9729hICagJuA61sLQh5P50jIScdSlKT5WMrgJGaLSA8wfUCuzUiq2t4N+u8U0UDTu3HqEooli2fO59CCzpemU3NvN4iT5lp4eiXZZ7EJUGwEpNWeOPGmh3PxdcXalaRu88LfBoWIE0ChyC0cvZycSOruChhajiow2//3JLsbp/B/jktx/NIJmoOk1NYTpnRaASytm3a2xugGrtYTOaqTeCkB0s4eyy++SaOOoyEauL4cox+nTqQ98ehXVWBxC1Nqt3tlMi9Jg4fm9KjmwZtkWx/WyHhA2WtuMq/L1mYMpijUDEGXIr6DfK7KxAdVeYoaxmrccAmNTQs5eCMqt+2Ooh3EWSfRsWutsPbhcwon9mUBsgD2xrEeKK6ZfKbRx9h1oNsQ0NmLz9kflpXWNLCbDmMXmdO2pR3kwdsnZQvCQEpMqE+B3XmcmGPPUpUAfr1XbbkwNdAbqEctDFmxKt4fMF3AILFT/7VYEHhSYkBWPIthRHnBLWsOppc5scsxYHBKge29Q2JrQhMtjumzUOQ4trT6Pu/I/d7SZEhcAV63QmIMEN1GYDDQnGB347mrk8jiAGOH1ROk/CYO69DZ5+QD4/RcV0ymJsgPv2y89As9ze1MyZXvJsw8JS/9PrKS/GLBPOhU7KYU+HqmZDo4=
  skip_cleanup: true
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/dist/*.zip"
  on:
    repo: noborus/trdsql
    tags: true
